"use client";
import { createGlobalStyle } from "styled-components";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const GlobalStyles = createGlobalStyle`
  body{
    padding: 0;
    margin: 0;
    font-family: "Roboto", sans-serif;
  }
`;

export default function RootLayout({ children }) {
	return (
		<>
			<GlobalStyles />
			<html lang="en">
				<body>{children}</body>
			</html>
		</>
	);
}
